apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mynamespace
configMapGenerator:
  - name: monitor-manifests
    files:
    - manifests/podmonitor.yaml
    - manifests/servicemonitor.yaml
resources:
- rbac.yaml
- dependent-apply-job.yaml